enableGlobalCache: true

globalFolder: ../.yarn/berry

defaultSemverRangePrefix: ''

preferReuse: true

packageExtensions:
  '@mikro-orm/postgresql@*':
    dependencies:
      '@mikro-orm/core': '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-remote.mjs
