defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

nodeLinker: pnp

npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  atls:
    npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  '@mikro-orm/postgresql@*':
    dependencies:
      '@mikro-orm/core': '*'
      '@types/pg': '*'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn.js
